name: Python Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  python-coverage:
    runs-on: ubuntu-latest
    name: Coverage Check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest==8.4.1
          pip install coverage==7.9
          pip install pytest-cov==6.2.1

      - name: Run tests with coverage
        run: python -m pytest --cov=src --cov-report=term-missing -v

      - name: Check coverage threshold
        run: python -m coverage report --fail-under=90